# Generated by Django 5.1.15 on 2026-04-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ko', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True)),
                ('name_ko', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ko', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('business_registration_no', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('insurance_info', models.JSONField(blank=True, default=dict)),
                ('bank_account', models.CharField(blank=True, default='', help_text='암호화 대상', max_length=200)),
                ('status', models.CharField(choices=[('active', '활성'), ('paused', '일시중단'), ('blacklisted', '차단')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title_ko', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle_ko', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=300)),
                ('description_ko', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('min_pax', models.IntegerField(default=1)),
                ('max_pax', models.IntegerField(default=4)),
                ('advance_booking_days', models.IntegerField(default=3)),
                ('cancellation_policy', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', '초안'), ('active', '공개'), ('paused', '일시중지'), ('archived', '보관')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('booking_count', models.IntegerField(default=0)),
                ('seo_meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_meta_description', models.CharField(blank=True, default='', max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='experiences.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='experiences.country')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(default='text-embedding-3-large', max_length=50)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='experiences.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('image', '이미지'), ('video', '영상')], default='image', max_length=10)),
                ('url', models.URLField()),
                ('display_order', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, default='', max_length=300)),
                ('is_cover', models.BooleanField(default=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='experiences.experience')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('additional_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('max_quantity', models.IntegerField(default=1)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='experiences.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name_ko', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bounding_box', models.JSONField(blank=True, help_text='{"sw":[lat,lng], "ne":[lat,lng]}', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='experiences.country')),
                ('hero_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='experiences.experiencemedia')),
            ],
            options={
                'ordering': ['display_order', 'code'],
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='experiences.region'),
        ),
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='experiences.tag'),
        ),
        migrations.AddField(
            model_name='experience',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='experiences.vendor'),
        ),
        migrations.CreateModel(
            name='VendorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='예: 25.00', max_digits=5)),
                ('settlement_cycle', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간')], default='monthly', max_length=10)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('contract_pdf_url', models.URLField(blank=True, default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='experiences.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('business_reg', '사업자등록증'), ('insurance', '보험증권'), ('contract', '계약서'), ('driver_license', '운전·조종면허'), ('safety_cert', '안전 인증')], max_length=20)),
                ('file_url', models.URLField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='experiences.vendor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.curator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('is_blocked', models.BooleanField(default=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='experiences.experience')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('experience', 'date', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['country', 'region', 'status'], name='experiences_country_f4c17f_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category', 'status'], name='experiences_categor_664c73_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_featured', 'status'], name='experiences_is_feat_a64dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['-published_at'], name='experiences_publish_5ec77e_idx'),
        ),
    ]
