# Generated by Django 5.1.15 on 2026-04-24 07:22

import experiences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='가능일 시작'),
        ),
        migrations.AddField(
            model_name='experience',
            name='available_to',
            field=models.DateField(blank=True, null=True, verbose_name='가능일 종료'),
        ),
        migrations.AddField(
            model_name='experience',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='네이버 블로그 스타일 에디터로 작성 — 글꼴·색·줄긋기·이미지·링크 자유롭게', verbose_name='상세 콘텐츠 (리치텍스트)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='0~100. 설정 시 프론트에서 원가에 짝대기 + 할인가 노출', verbose_name='할인 %'),
        ),
        migrations.AddField(
            model_name='experiencemedia',
            name='file',
            field=models.FileField(blank=True, help_text='JPG · PNG · GIF · WEBP · MP4 · PDF 등. 외부 URL만 쓸 경우 비워도 됨.', null=True, upload_to=experiences.models.experience_file_upload_path, verbose_name='파일 업로드'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='정가 (KRW)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_ko',
            field=models.TextField(blank=True, default='', help_text='리스트·카드 노출용 요약', verbose_name='짧은 설명'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration_minutes',
            field=models.IntegerField(default=0, verbose_name='소요시간(분)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='상품명 (영)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_ko',
            field=models.CharField(max_length=200, verbose_name='상품명 (한)'),
        ),
        migrations.AlterField(
            model_name='experiencemedia',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='접근성 대체 텍스트', max_length=300),
        ),
        migrations.AlterField(
            model_name='experiencemedia',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='experiencemedia',
            name='type',
            field=models.CharField(choices=[('image', '이미지'), ('video', '영상'), ('document', '문서')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='experiencemedia',
            name='url',
            field=models.URLField(blank=True, default='', help_text='업로드 대신 외부 이미지 URL 사용 시', verbose_name='외부 URL'),
        ),
    ]
