# Generated by Django 5.1.15 on 2026-04-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_available_from_experience_available_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'code'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['display_order', 'code'], 'verbose_name': '국가', 'verbose_name_plural': '국가'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-is_featured', '-published_at'], 'verbose_name': '경험 상품', 'verbose_name_plural': '경험 상품'},
        ),
        migrations.AlterModelOptions(
            name='experienceembedding',
            options={'verbose_name': '경험 임베딩 (RAG)', 'verbose_name_plural': '경험 임베딩 (RAG)'},
        ),
        migrations.AlterModelOptions(
            name='experiencemedia',
            options={'ordering': ['display_order'], 'verbose_name': '경험 이미지·영상', 'verbose_name_plural': '경험 이미지·영상'},
        ),
        migrations.AlterModelOptions(
            name='experienceoption',
            options={'verbose_name': '경험 옵션', 'verbose_name_plural': '경험 옵션'},
        ),
        migrations.AlterModelOptions(
            name='experienceschedule',
            options={'ordering': ['date', 'start_time'], 'verbose_name': '경험 일정 슬롯', 'verbose_name_plural': '경험 일정 슬롯'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['display_order', 'code'], 'verbose_name': '지역', 'verbose_name_plural': '지역'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': '공급사 (벤더)', 'verbose_name_plural': '공급사 (벤더)'},
        ),
        migrations.AlterModelOptions(
            name='vendorcontract',
            options={'verbose_name': '공급사 계약', 'verbose_name_plural': '공급사 계약'},
        ),
        migrations.AlterModelOptions(
            name='vendordocument',
            options={'verbose_name': '공급사 증빙 파일', 'verbose_name_plural': '공급사 증빙 파일'},
        ),
    ]
