# Generated by Django 5.1.15 on 2026-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_category_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='home_pick_order',
            field=models.IntegerField(blank=True, db_index=True, help_text='작을수록 앞. 비워두면 published_at 정렬', null=True, verbose_name='핀 고정 순서'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_monthly_popular',
            field=models.BooleanField(db_index=True, default=False, help_text='"월간 인기" 풀에 노출. 추천과 독립적으로 운영', verbose_name='월간 인기'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_new_arrival',
            field=models.BooleanField(db_index=True, default=False, help_text='"신상" 풀에 노출. published_at만 보지 말고 명시적으로 지정', verbose_name='신상'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='홈/Experiences 상단 "마음 PICK" 풀에 노출', verbose_name='추천 (마음 PICK)'),
        ),
    ]
