# Generated by Django 5.1.15 on 2026-04-24 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('experiences', '0003_alter_category_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curator',
            options={'verbose_name': '큐레이터', 'verbose_name_plural': '큐레이터'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': '멤버십 가입', 'verbose_name_plural': '멤버십 가입'},
        ),
        migrations.AlterModelOptions(
            name='membershiptier',
            options={'verbose_name': '멤버십 등급', 'verbose_name_plural': '멤버십 등급'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '회원 프로필', 'verbose_name_plural': '회원 프로필'},
        ),
        migrations.CreateModel(
            name='MemberIntakeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('age_range', models.CharField(choices=[('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대'), ('60plus', '60대 이상'), ('na', '공개하지 않음')], default='na', max_length=12)),
                ('residence_city', models.CharField(blank=True, default='', help_text='거주 시/도', max_length=60)),
                ('residence_district', models.CharField(blank=True, default='', help_text='거주 구/동 (선택)', max_length=80)),
                ('occupation', models.CharField(blank=True, default='', help_text='직업·직함', max_length=120)),
                ('company', models.CharField(blank=True, default='', help_text='소속 (선택)', max_length=120)),
                ('marital_status', models.CharField(choices=[('single', '미혼'), ('married', '기혼'), ('partnered', '장기 파트너'), ('divorced', '이혼'), ('na', '공개하지 않음')], default='na', max_length=12)),
                ('annual_income_range', models.CharField(choices=[('lt_100m', '1억 미만'), ('100_300m', '1억 – 3억'), ('300_500m', '3억 – 5억'), ('500_1b', '5억 – 10억'), ('gte_1b', '10억 이상'), ('na', '공개하지 않음')], default='na', max_length=12)),
                ('asset_range', models.CharField(choices=[('lt_500m', '5억 미만'), ('500m_1b', '5억 – 10억'), ('1b_3b', '10억 – 30억'), ('3b_10b', '30억 – 100억'), ('gte_10b', '100억 이상'), ('na', '공개하지 않음')], default='na', max_length=12)),
                ('budget_per_experience', models.CharField(choices=[('lt_1m', '100만원 미만'), ('1m_3m', '100만 – 300만원'), ('3m_5m', '300만 – 500만원'), ('5m_10m', '500만 – 1,000만원'), ('gte_10m', '1,000만원 이상'), ('na', '상담 후 결정')], default='na', max_length=12)),
                ('preferred_months', models.JSONField(blank=True, default=list, help_text='선호 월 1~12 리스트 (예: [4, 5, 10])')),
                ('companion_types', models.JSONField(blank=True, default=list, help_text='동행 유형 다중선택 — COMPANION_CHOICES 의 key 리스트')),
                ('special_occasions', models.TextField(blank=True, default='', help_text='기념일·특별 행사·드림 경험 자유 서술')),
                ('referral_source', models.CharField(choices=[('search', '검색'), ('sns', 'SNS (Instagram/YouTube)'), ('press', '언론·매거진'), ('friend', '지인 추천'), ('curator', '큐레이터 초청'), ('other', '기타')], default='other', max_length=12)),
                ('referral_detail', models.CharField(blank=True, default='', help_text='추천인 이름·SNS 계정 등 (선택)', max_length=200)),
                ('consent_privacy', models.BooleanField(default=False, help_text='민감정보 수집 동의 (필수)')),
                ('consent_marketing', models.BooleanField(default=False, help_text='마케팅 수신 동의 (선택)')),
                ('consent_profiling', models.BooleanField(default=False, help_text='큐레이션 프로파일링 분석 동의 (선택)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='intake_surveys', to='experiences.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '회원 인테이크 설문',
                'verbose_name_plural': '회원 인테이크 설문',
            },
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('naver', 'Naver'), ('mock', 'Mock (dev)')], max_length=16)),
                ('provider_uid', models.CharField(max_length=255)),
                ('email_at_signup', models.EmailField(blank=True, default='', max_length=254)),
                ('raw_name', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '소셜 아이덴티티',
                'verbose_name_plural': '소셜 아이덴티티',
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
