# Generated by Django 5.1.15 on 2026-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_curator_options_alter_membership_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, default='', help_text='서비스 전역에서 유니크한 닉네임 (2~24자, 공백 허용 안 함).', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('nickname', ''), _negated=True), fields=('nickname',), name='unique_nickname_when_set'),
        ),
    ]
