# Generated by Django 5.1.15 on 2026-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_method',
            field=models.CharField(blank=True, default='', help_text='instagram / linkedin / interview / kyc 등', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
