# Generated by Django 5.1.15 on 2026-04-24 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_status', models.CharField(choices=[('browsing', '탐색중'), ('curation_requested', '큐레이션 요청됨'), ('booked', '예약됨')], default='browsing', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('retrieved_experience_ids', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, default='', max_length=50)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='curation.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ko', models.CharField(max_length=50)),
                ('name_en', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('hero_experiences', models.ManyToManyField(blank=True, related_name='hero_for_types', to='experiences.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalityTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_opted_in_curation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
                ('result_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='curation.personalitytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('preferred_date_start', models.DateField(blank=True, null=True)),
                ('preferred_date_end', models.DateField(blank=True, null=True)),
                ('budget_min', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('pax_count', models.IntegerField(default=2)),
                ('occasion', models.CharField(choices=[('birthday', '생일'), ('anniversary', '기념일'), ('proposal', '프로포즈'), ('business', '비즈니스'), ('self_reward', '자기보상'), ('other', '기타')], default='other', max_length=20)),
                ('free_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', '신규'), ('assigned', '배정'), ('proposed', '제안발송'), ('booked', '예약완료'), ('declined', '거절'), ('closed', '종결')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('web_form', '웹 폼'), ('chatbot', '챗봇'), ('phone', '전화'), ('kakao', '카카오')], default='web_form', max_length=20)),
                ('assigned_curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_requests', to='accounts.curator')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_requests', to='experiences.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_requests', to=settings.AUTH_USER_MODEL)),
                ('personality_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curation.personalitytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=True, help_text='예약 데이터 기반 자동 true')),
                ('is_public', models.BooleanField(default=True)),
                ('curator_reply', models.TextField(blank=True, default='')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('option_label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('narrative', models.TextField(blank=True, default='')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('pdf_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', '초안'), ('sent', '발송'), ('accepted', '채택'), ('declined', '거절')], default='draft', max_length=20)),
                ('experience_refs', models.ManyToManyField(blank=True, related_name='+', to='experiences.experience')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='curation.curationrequest')),
            ],
            options={
                'unique_together': {('request', 'option_label')},
            },
        ),
        migrations.CreateModel(
            name='PersonalityTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question_code', models.CharField(max_length=10)),
                ('answer_code', models.CharField(max_length=30)),
                ('answer_weight', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='curation.personalitytestsession')),
            ],
            options={
                'unique_together': {('session', 'question_code')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_by', to='experiences.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'experience')},
            },
        ),
    ]
