# Generated by Django 5.1.15 on 2026-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': '챗봇 메시지', 'verbose_name_plural': '챗봇 메시지'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': '챗봇 세션', 'verbose_name_plural': '챗봇 세션'},
        ),
        migrations.AlterModelOptions(
            name='curationproposal',
            options={'verbose_name': '큐레이션 제안', 'verbose_name_plural': '큐레이션 제안'},
        ),
        migrations.AlterModelOptions(
            name='curationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '큐레이션 문의', 'verbose_name_plural': '큐레이션 문의'},
        ),
        migrations.AlterModelOptions(
            name='personalitytestanswer',
            options={'verbose_name': '성향 테스트 답변', 'verbose_name_plural': '성향 테스트 답변'},
        ),
        migrations.AlterModelOptions(
            name='personalitytestsession',
            options={'verbose_name': '성향 테스트 응시', 'verbose_name_plural': '성향 테스트 응시'},
        ),
        migrations.AlterModelOptions(
            name='personalitytype',
            options={'verbose_name': '성향 유형', 'verbose_name_plural': '성향 유형'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '후기', 'verbose_name_plural': '후기'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': '찜', 'verbose_name_plural': '찜'},
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='avoid_note',
            field=models.TextField(blank=True, default='', help_text='피하면 좋을 경험 유형 (선택)'),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='"이런 타입의 사람은 … 한 경향이 있습니다" 3~5 문장'),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='recommended_categories',
            field=models.JSONField(blank=True, default=list, help_text='추천 카테고리 코드 리스트 (카드 필터 힌트)'),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='traits',
            field=models.JSONField(blank=True, default=list, help_text='성향 키워드 리스트 (예: ["조용함","섬세함","느린 리듬"])'),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='why_fits',
            field=models.TextField(blank=True, default='', help_text='"그래서 이런 경험이 어울립니다" 3~5 문장'),
        ),
        migrations.AlterField(
            model_name='personalitytype',
            name='description',
            field=models.TextField(blank=True, default='', help_text='한 줄 요약 (배너용)'),
        ),
    ]
