# Generated by Django 5.1.15 on 2026-04-24 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('booking_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', '결제대기'), ('confirmed', '확정'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('refunded', '환불')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('pax_count', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, help_text='벤더 공제 수수료 (자동계산)', max_digits=12)),
                ('special_request', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.curator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experiences.experience')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiences.experienceoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('tosspayments', 'TossPayments'), ('bank_transfer', '계좌이체'), ('manual', '수기')], max_length=20)),
                ('provider_tx_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('status', models.CharField(choices=[('pending', '대기'), ('paid', '완료'), ('failed', '실패'), ('refunded', '전액환불'), ('partial_refunded', '부분환불')], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('provider_refund_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('requested', '요청'), ('approved', '승인'), ('completed', '완료'), ('rejected', '반려')], default='requested', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.curator')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bookings.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bookings.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_at'], name='bookings_bo_schedul_526bf0_idx'),
        ),
    ]
