# Generated by Django 5.1.15 on 2026-04-25 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('experiences', '0003_alter_category_options_alter_country_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': '예약', 'verbose_name_plural': '예약'},
        ),
        migrations.AlterModelOptions(
            name='bookingitem',
            options={'verbose_name': '예약 라인', 'verbose_name_plural': '예약 라인'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '결제', 'verbose_name_plural': '결제'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': '환불', 'verbose_name_plural': '환불'},
        ),
        migrations.AddField(
            model_name='booking',
            name='sharing_mode',
            field=models.CharField(choices=[('private', '단독 (다른 팀 합류 불가)'), ('open', '합석 허용')], default='private', help_text='사용자 의사: 단독 / 합석 허용', max_length=10),
        ),
        migrations.CreateModel(
            name='SessionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('sharing_mode', models.CharField(choices=[('private', '단독 (다른 팀 합류 불가)'), ('open', '합석 허용')], db_index=True, default='private', max_length=10)),
                ('capacity', models.IntegerField(default=1)),
                ('pax_taken', models.IntegerField(default=0)),
                ('is_full', models.BooleanField(db_index=True, default=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_groups', to='experiences.experience')),
            ],
            options={
                'verbose_name': '세션 그룹',
                'verbose_name_plural': '세션 그룹',
                'ordering': ['scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('session_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='bookings.sessiongroup')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='session_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.sessiongroup'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('user', '유저'), ('system', '시스템')], default='user', max_length=10)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.chatroom')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='bookings_ch_room_id_96f487_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sessiongroup',
            index=models.Index(fields=['experience', 'scheduled_date', 'sharing_mode', 'is_full'], name='bookings_se_experie_85215d_idx'),
        ),
    ]
