# Generated by Django 5.1.15 on 2026-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_bookingitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sharing_mode',
            field=models.CharField(choices=[('private', '단독 이용 (다른 팀 합류 불가)'), ('friends_only', '지인만 동반'), ('open', '오픈 멤버 모집 (다른 팀 합류 가능)')], default='private', help_text='사용자 의사: 단독 / 지인만 / 오픈 합석', max_length=16),
        ),
        migrations.AlterField(
            model_name='sessiongroup',
            name='sharing_mode',
            field=models.CharField(choices=[('private', '단독 이용 (다른 팀 합류 불가)'), ('friends_only', '지인만 동반'), ('open', '오픈 멤버 모집 (다른 팀 합류 가능)')], db_index=True, default='private', max_length=16),
        ),
    ]
